// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PO2_projekt.Data;

#nullable disable

namespace PO2projekt.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20250606104635_AddDueDateToBorrowing")]
    partial class AddDueDateToBorrowing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PO2_projekt.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Adam",
                            LastName = "Mickiewicz"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Henryk",
                            LastName = "Sienkiewicz"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Olga",
                            LastName = "Tokarczuk"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Stephen",
                            LastName = "King"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "J.K.",
                            LastName = "Rowling"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Stanisław",
                            LastName = "Lem"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "J.R.R.",
                            LastName = "Tolkien"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Andrzej",
                            LastName = "Sapkowski"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Agatha",
                            LastName = "Christie"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Haruki",
                            LastName = "Murakami"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Dan",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Eliza",
                            LastName = "Orzeszkowa"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Bolesław",
                            LastName = "Prus"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "George",
                            LastName = "Orwell"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Jo Nesbø",
                            LastName = ""
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Fiodor",
                            LastName = "Dostojewski"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Gabriel",
                            LastName = "García Márquez"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Umberto",
                            LastName = "Eco"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Margaret",
                            LastName = "Atwood"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "C.S.",
                            LastName = "Lewis"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Ernest",
                            LastName = "Hemingway"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "William",
                            LastName = "Shakespeare"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Charles",
                            LastName = "Dickens"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Jane",
                            LastName = "Austen"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Emily",
                            LastName = "Brontë"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Mark",
                            LastName = "Twain"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Franz",
                            LastName = "Kafka"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Antoine",
                            LastName = "de Saint-Exupéry"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Jules",
                            LastName = "Verne"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Isaac",
                            LastName = "Asimov"
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Terry",
                            LastName = "Pratchett"
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Michael",
                            LastName = "Ende"
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Astrid",
                            LastName = "Lindgren"
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Lewis",
                            LastName = "Carroll"
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Harlan",
                            LastName = "Coben"
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Mario",
                            LastName = "Puzo"
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Carlos",
                            LastName = "Ruiz Zafón"
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Patrick",
                            LastName = "Süskind"
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Khaled",
                            LastName = "Hosseini"
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Harper",
                            LastName = "Lee"
                        });
                });

            modelBuilder.Entity("PO2_projekt.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("Copies")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Copies = 5,
                            Title = "Pan Tadeusz",
                            YearPublished = 1834
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Copies = 6,
                            Title = "Quo Vadis",
                            YearPublished = 1896
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Copies = 7,
                            Title = "Bieguni",
                            YearPublished = 2007
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 7,
                            Copies = 5,
                            Title = "Lśnienie",
                            YearPublished = 1977
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Copies = 6,
                            Title = "Harry Potter i Kamień Filozoficzny",
                            YearPublished = 1997
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Copies = 7,
                            Title = "Solaris",
                            YearPublished = 1961
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 26,
                            Copies = 5,
                            Title = "Władca Pierścieni",
                            YearPublished = 1954
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 26,
                            Copies = 6,
                            Title = "Krew elfów",
                            YearPublished = 1994
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Copies = 7,
                            Title = "Morderstwo w Orient Expressie",
                            YearPublished = 1934
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            Copies = 5,
                            Title = "Norwegian Wood",
                            YearPublished = 1987
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Copies = 6,
                            Title = "Kod Leonarda da Vinci",
                            YearPublished = 2003
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Copies = 7,
                            Title = "Nad Niemnem",
                            YearPublished = 1888
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Copies = 5,
                            Title = "Lalka",
                            YearPublished = 1890
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 6,
                            Copies = 6,
                            Title = "Rok 1984",
                            YearPublished = 1949
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Copies = 7,
                            Title = "Człowiek nietoperz",
                            YearPublished = 1997
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 18,
                            Copies = 5,
                            Title = "Sto lat samotności",
                            YearPublished = 1967
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Copies = 6,
                            Title = "Imię róży",
                            YearPublished = 1980
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 19,
                            Copies = 7,
                            Title = "Opowieść podręcznej",
                            YearPublished = 1985
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 26,
                            Copies = 5,
                            Title = "Lew, czarownica i stara szafa",
                            YearPublished = 1950
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 20,
                            Copies = 6,
                            Title = "Stary człowiek i morze",
                            YearPublished = 1952
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            Copies = 7,
                            Title = "Romeo i Julia",
                            YearPublished = 1597
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 29,
                            Copies = 5,
                            Title = "Wielkie nadzieje",
                            YearPublished = 1861
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 8,
                            Copies = 6,
                            Title = "Duma i uprzedzenie",
                            YearPublished = 1813
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 8,
                            Copies = 7,
                            Title = "Wichrowe wzgórza",
                            YearPublished = 1847
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 9,
                            Copies = 5,
                            Title = "Przygody Tomka Sawyera",
                            YearPublished = 1876
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 8,
                            Copies = 6,
                            Title = "Proces",
                            YearPublished = 1925
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 13,
                            Copies = 7,
                            Title = "Mały Książę",
                            YearPublished = 1943
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 9,
                            Copies = 5,
                            Title = "W 80 dni dookoła świata",
                            YearPublished = 1873
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 25,
                            Copies = 6,
                            Title = "Fundacja",
                            YearPublished = 1951
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 26,
                            Copies = 7,
                            Title = "Kolor magii",
                            YearPublished = 1983
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 13,
                            Copies = 5,
                            Title = "Momo",
                            YearPublished = 1973
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 13,
                            Copies = 6,
                            Title = "Dzieci z Bullerbyn",
                            YearPublished = 1947
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 13,
                            Copies = 7,
                            Title = "Alicja w Krainie Czarów",
                            YearPublished = 1865
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 24,
                            Copies = 5,
                            Title = "Nie mów nikomu",
                            YearPublished = 2001
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 9,
                            Copies = 6,
                            Title = "Ojciec chrzestny",
                            YearPublished = 1969
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 29,
                            Copies = 7,
                            Title = "Cień wiatru",
                            YearPublished = 2001
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 8,
                            Copies = 5,
                            Title = "Pachnidło",
                            YearPublished = 1985
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 9,
                            Copies = 6,
                            Title = "Chłopiec z latawcem",
                            YearPublished = 2003
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 8,
                            Copies = 7,
                            Title = "Zabić drozda",
                            YearPublished = 1960
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 8,
                            Copies = 5,
                            Title = "Pięćdziesiąt twarzy Greya",
                            YearPublished = 2011
                        });
                });

            modelBuilder.Entity("PO2_projekt.Models.BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 5
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 6
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 7
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 8
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 9
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 10
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 11
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 12
                        },
                        new
                        {
                            BookId = 13,
                            AuthorId = 13
                        },
                        new
                        {
                            BookId = 14,
                            AuthorId = 14
                        },
                        new
                        {
                            BookId = 15,
                            AuthorId = 15
                        },
                        new
                        {
                            BookId = 16,
                            AuthorId = 16
                        },
                        new
                        {
                            BookId = 17,
                            AuthorId = 17
                        },
                        new
                        {
                            BookId = 18,
                            AuthorId = 18
                        },
                        new
                        {
                            BookId = 19,
                            AuthorId = 19
                        },
                        new
                        {
                            BookId = 20,
                            AuthorId = 20
                        },
                        new
                        {
                            BookId = 21,
                            AuthorId = 21
                        },
                        new
                        {
                            BookId = 22,
                            AuthorId = 22
                        },
                        new
                        {
                            BookId = 23,
                            AuthorId = 23
                        },
                        new
                        {
                            BookId = 24,
                            AuthorId = 24
                        },
                        new
                        {
                            BookId = 25,
                            AuthorId = 25
                        },
                        new
                        {
                            BookId = 26,
                            AuthorId = 26
                        },
                        new
                        {
                            BookId = 27,
                            AuthorId = 27
                        },
                        new
                        {
                            BookId = 28,
                            AuthorId = 28
                        },
                        new
                        {
                            BookId = 29,
                            AuthorId = 29
                        },
                        new
                        {
                            BookId = 30,
                            AuthorId = 30
                        },
                        new
                        {
                            BookId = 31,
                            AuthorId = 31
                        },
                        new
                        {
                            BookId = 32,
                            AuthorId = 32
                        },
                        new
                        {
                            BookId = 33,
                            AuthorId = 33
                        },
                        new
                        {
                            BookId = 34,
                            AuthorId = 34
                        },
                        new
                        {
                            BookId = 35,
                            AuthorId = 35
                        },
                        new
                        {
                            BookId = 36,
                            AuthorId = 36
                        },
                        new
                        {
                            BookId = 37,
                            AuthorId = 37
                        },
                        new
                        {
                            BookId = 38,
                            AuthorId = 38
                        },
                        new
                        {
                            BookId = 39,
                            AuthorId = 39
                        },
                        new
                        {
                            BookId = 40,
                            AuthorId = 40
                        });
                });

            modelBuilder.Entity("PO2_projekt.Models.Borrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Returned")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Borrowings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            BorrowDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            BorrowDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            BorrowDate = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            BorrowDate = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            BookId = 5,
                            BorrowDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            BookId = 6,
                            BorrowDate = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            BookId = 7,
                            BorrowDate = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            BookId = 8,
                            BorrowDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            BookId = 9,
                            BorrowDate = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            BookId = 10,
                            BorrowDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            BookId = 11,
                            BorrowDate = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            BookId = 12,
                            BorrowDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            BookId = 13,
                            BorrowDate = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            BookId = 14,
                            BorrowDate = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            BookId = 15,
                            BorrowDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            BookId = 16,
                            BorrowDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            BookId = 17,
                            BorrowDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            BookId = 18,
                            BorrowDate = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            BookId = 19,
                            BorrowDate = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            BookId = 20,
                            BorrowDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 20
                        },
                        new
                        {
                            Id = 21,
                            BookId = 21,
                            BorrowDate = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 21
                        },
                        new
                        {
                            Id = 22,
                            BookId = 22,
                            BorrowDate = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 22
                        },
                        new
                        {
                            Id = 23,
                            BookId = 23,
                            BorrowDate = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 23
                        },
                        new
                        {
                            Id = 24,
                            BookId = 24,
                            BorrowDate = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 24
                        },
                        new
                        {
                            Id = 25,
                            BookId = 25,
                            BorrowDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 25
                        },
                        new
                        {
                            Id = 26,
                            BookId = 26,
                            BorrowDate = new DateTime(2024, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 26
                        },
                        new
                        {
                            Id = 27,
                            BookId = 27,
                            BorrowDate = new DateTime(2024, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 27
                        },
                        new
                        {
                            Id = 28,
                            BookId = 28,
                            BorrowDate = new DateTime(2024, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 28
                        },
                        new
                        {
                            Id = 29,
                            BookId = 29,
                            BorrowDate = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 29
                        },
                        new
                        {
                            Id = 30,
                            BookId = 30,
                            BorrowDate = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 30
                        },
                        new
                        {
                            Id = 31,
                            BookId = 31,
                            BorrowDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 31
                        },
                        new
                        {
                            Id = 32,
                            BookId = 32,
                            BorrowDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 32
                        },
                        new
                        {
                            Id = 33,
                            BookId = 33,
                            BorrowDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 33
                        },
                        new
                        {
                            Id = 34,
                            BookId = 34,
                            BorrowDate = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 34
                        },
                        new
                        {
                            Id = 35,
                            BookId = 35,
                            BorrowDate = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 35
                        },
                        new
                        {
                            Id = 36,
                            BookId = 36,
                            BorrowDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 36
                        },
                        new
                        {
                            Id = 37,
                            BookId = 37,
                            BorrowDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 37
                        },
                        new
                        {
                            Id = 38,
                            BookId = 38,
                            BorrowDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 38
                        },
                        new
                        {
                            Id = 39,
                            BookId = 39,
                            BorrowDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 39
                        },
                        new
                        {
                            Id = 40,
                            BookId = 40,
                            BorrowDate = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Returned = false,
                            UserId = 40
                        });
                });

            modelBuilder.Entity("PO2_projekt.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Powieść"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kryminał"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fantastyka"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Biografia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Poezja"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Dramat"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Romans"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Przygodowa"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Nauka"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Esej"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Reportaż"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Literatura dziecięca"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Literatura młodzieżowa"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Publicystyka"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Satyra"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Literatura faktu"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Historyczna"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Obyczajowa"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Psychologiczna"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Filozofia"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Religia"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Podróżnicza"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Sensacja"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Science fiction"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Komiks"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Literatura piękna"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Literatura współczesna"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Literatura klasyczna"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Antologia"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Opowiadania"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Nowela"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Literatura kobieca"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Poradnik"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Motywacyjna"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Ekonomia"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Biznes"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Technologia"
                        });
                });

            modelBuilder.Entity("PO2_projekt.Models.Reader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Readers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jan.kowalski@example.com",
                            FirstName = "Jan",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "anna.nowak@example.com",
                            FirstName = "Anna",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "piotr.zielinski@example.com",
                            FirstName = "Piotr",
                            LastName = "Zieliński"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria.wisniewska@example.com",
                            FirstName = "Maria",
                            LastName = "Wiśniewska"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "krzysztof.wojcik@example.com",
                            FirstName = "Krzysztof",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "agnieszka.krawczyk@example.com",
                            FirstName = "Agnieszka",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tomasz.mazur@example.com",
                            FirstName = "Tomasz",
                            LastName = "Mazur"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "katarzyna.dabrowska@example.com",
                            FirstName = "Katarzyna",
                            LastName = "Dąbrowska"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "michal.lewandowski@example.com",
                            FirstName = "Michał",
                            LastName = "Lewandowski"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "barbara.zajac@example.com",
                            FirstName = "Barbara",
                            LastName = "Zając"
                        },
                        new
                        {
                            Id = 11,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pawel.krol@example.com",
                            FirstName = "Paweł",
                            LastName = "Król"
                        },
                        new
                        {
                            Id = 12,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ewa.wieczorek@example.com",
                            FirstName = "Ewa",
                            LastName = "Wieczorek"
                        },
                        new
                        {
                            Id = 13,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "andrzej.jankowski@example.com",
                            FirstName = "Andrzej",
                            LastName = "Jankowski"
                        },
                        new
                        {
                            Id = 14,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "magdalena.witkowska@example.com",
                            FirstName = "Magdalena",
                            LastName = "Witkowska"
                        },
                        new
                        {
                            Id = 15,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "marek.kowalczyk@example.com",
                            FirstName = "Marek",
                            LastName = "Kowalczyk"
                        },
                        new
                        {
                            Id = 16,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "joanna.szymanska@example.com",
                            FirstName = "Joanna",
                            LastName = "Szymańska"
                        },
                        new
                        {
                            Id = 17,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "grzegorz.wozniak@example.com",
                            FirstName = "Grzegorz",
                            LastName = "Woźniak"
                        },
                        new
                        {
                            Id = 18,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "aleksandra.kozlowska@example.com",
                            FirstName = "Aleksandra",
                            LastName = "Kozłowska"
                        },
                        new
                        {
                            Id = 19,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lukasz.jablonski@example.com",
                            FirstName = "Łukasz",
                            LastName = "Jabłoński"
                        },
                        new
                        {
                            Id = 20,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "monika.pawlak@example.com",
                            FirstName = "Monika",
                            LastName = "Pawlak"
                        },
                        new
                        {
                            Id = 21,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "natalia.sikora@example.com",
                            FirstName = "Natalia",
                            LastName = "Sikora"
                        },
                        new
                        {
                            Id = 22,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "rafal.baran@example.com",
                            FirstName = "Rafał",
                            LastName = "Baran"
                        },
                        new
                        {
                            Id = 23,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "karolina.sadowska@example.com",
                            FirstName = "Karolina",
                            LastName = "Sadowska"
                        },
                        new
                        {
                            Id = 24,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dariusz.gorski@example.com",
                            FirstName = "Dariusz",
                            LastName = "Górski"
                        },
                        new
                        {
                            Id = 25,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patrycja.czarnecka@example.com",
                            FirstName = "Patrycja",
                            LastName = "Czarnecka"
                        },
                        new
                        {
                            Id = 26,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "wojciech.kaczmarek@example.com",
                            FirstName = "Wojciech",
                            LastName = "Kaczmarek"
                        },
                        new
                        {
                            Id = 27,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sylwia.piotrowska@example.com",
                            FirstName = "Sylwia",
                            LastName = "Piotrowska"
                        },
                        new
                        {
                            Id = 28,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mariusz.adamski@example.com",
                            FirstName = "Mariusz",
                            LastName = "Adamski"
                        },
                        new
                        {
                            Id = 29,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "izabela.wrobel@example.com",
                            FirstName = "Izabela",
                            LastName = "Wróbel"
                        },
                        new
                        {
                            Id = 30,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sebastian.lis@example.com",
                            FirstName = "Sebastian",
                            LastName = "Lis"
                        },
                        new
                        {
                            Id = 31,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "beata.michalska@example.com",
                            FirstName = "Beata",
                            LastName = "Michalska"
                        },
                        new
                        {
                            Id = 32,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "adrian.kubiak@example.com",
                            FirstName = "Adrian",
                            LastName = "Kubiak"
                        },
                        new
                        {
                            Id = 33,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "wiktoria.duda@example.com",
                            FirstName = "Wiktoria",
                            LastName = "Duda"
                        },
                        new
                        {
                            Id = 34,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "szymon.bak@example.com",
                            FirstName = "Szymon",
                            LastName = "Bąk"
                        },
                        new
                        {
                            Id = 35,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "emilia.jaworska@example.com",
                            FirstName = "Emilia",
                            LastName = "Jaworska"
                        },
                        new
                        {
                            Id = 36,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mateusz.walczak@example.com",
                            FirstName = "Mateusz",
                            LastName = "Walczak"
                        },
                        new
                        {
                            Id = 37,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "julia.szymanska@example.com",
                            FirstName = "Julia",
                            LastName = "Szymańska"
                        },
                        new
                        {
                            Id = 38,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "artur.pawlowski@example.com",
                            FirstName = "Artur",
                            LastName = "Pawłowski"
                        },
                        new
                        {
                            Id = 39,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "paulina.witkowska@example.com",
                            FirstName = "Paulina",
                            LastName = "Witkowska"
                        },
                        new
                        {
                            Id = 40,
                            Country = "Polska",
                            CreateAt = new DateTime(2023, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "kamil.rutkowski@example.com",
                            FirstName = "Kamil",
                            LastName = "Rutkowski"
                        });
                });

            modelBuilder.Entity("PO2_projekt.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Expiration = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            Expiration = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            Expiration = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            Expiration = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            BookId = 5,
                            Expiration = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            BookId = 6,
                            Expiration = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            BookId = 7,
                            Expiration = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            BookId = 8,
                            Expiration = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            BookId = 9,
                            Expiration = new DateTime(2024, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            BookId = 10,
                            Expiration = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            BookId = 11,
                            Expiration = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            BookId = 12,
                            Expiration = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            BookId = 13,
                            Expiration = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            BookId = 14,
                            Expiration = new DateTime(2024, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            BookId = 15,
                            Expiration = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            BookId = 16,
                            Expiration = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            BookId = 17,
                            Expiration = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            BookId = 18,
                            Expiration = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            BookId = 19,
                            Expiration = new DateTime(2024, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            BookId = 20,
                            Expiration = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 20
                        },
                        new
                        {
                            Id = 21,
                            BookId = 21,
                            Expiration = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 21
                        },
                        new
                        {
                            Id = 22,
                            BookId = 22,
                            Expiration = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 22
                        },
                        new
                        {
                            Id = 23,
                            BookId = 23,
                            Expiration = new DateTime(2024, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 23
                        },
                        new
                        {
                            Id = 24,
                            BookId = 24,
                            Expiration = new DateTime(2024, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 24
                        },
                        new
                        {
                            Id = 25,
                            BookId = 25,
                            Expiration = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 25
                        },
                        new
                        {
                            Id = 26,
                            BookId = 26,
                            Expiration = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 26
                        },
                        new
                        {
                            Id = 27,
                            BookId = 27,
                            Expiration = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 27
                        },
                        new
                        {
                            Id = 28,
                            BookId = 28,
                            Expiration = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 28
                        },
                        new
                        {
                            Id = 29,
                            BookId = 29,
                            Expiration = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 29
                        },
                        new
                        {
                            Id = 30,
                            BookId = 30,
                            Expiration = new DateTime(2024, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 30
                        },
                        new
                        {
                            Id = 31,
                            BookId = 31,
                            Expiration = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 31
                        },
                        new
                        {
                            Id = 32,
                            BookId = 32,
                            Expiration = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 32
                        },
                        new
                        {
                            Id = 33,
                            BookId = 33,
                            Expiration = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 33
                        },
                        new
                        {
                            Id = 34,
                            BookId = 34,
                            Expiration = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 34
                        },
                        new
                        {
                            Id = 35,
                            BookId = 35,
                            Expiration = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 35
                        },
                        new
                        {
                            Id = 36,
                            BookId = 36,
                            Expiration = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 36
                        },
                        new
                        {
                            Id = 37,
                            BookId = 37,
                            Expiration = new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 37
                        },
                        new
                        {
                            Id = 38,
                            BookId = 38,
                            Expiration = new DateTime(2024, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 38
                        },
                        new
                        {
                            Id = 39,
                            BookId = 39,
                            Expiration = new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 39
                        },
                        new
                        {
                            Id = 40,
                            BookId = 40,
                            Expiration = new DateTime(2024, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAt = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 40
                        });
                });

            modelBuilder.Entity("PO2_projekt.Models.Book", b =>
                {
                    b.HasOne("PO2_projekt.Models.Category", "Category")
                        .WithMany("Book")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PO2_projekt.Models.BookAuthor", b =>
                {
                    b.HasOne("PO2_projekt.Models.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PO2_projekt.Models.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("PO2_projekt.Models.Borrowing", b =>
                {
                    b.HasOne("PO2_projekt.Models.Book", "Book")
                        .WithMany("Borrowings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PO2_projekt.Models.Reader", "User")
                        .WithMany("Borrowings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PO2_projekt.Models.Reservation", b =>
                {
                    b.HasOne("PO2_projekt.Models.Book", "Book")
                        .WithMany("Reservations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PO2_projekt.Models.Reader", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PO2_projekt.Models.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("PO2_projekt.Models.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("Borrowings");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("PO2_projekt.Models.Category", b =>
                {
                    b.Navigation("Book");
                });

            modelBuilder.Entity("PO2_projekt.Models.Reader", b =>
                {
                    b.Navigation("Borrowings");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
